name: Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                toolchain: [nightly]

        name: Build ${{ matrix.os }} - ${{ matrix.toolchain }}

        runs-on: ${{ matrix.os }}

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust ${{ matrix.toolchain }}
              uses: actions-rs/toolchain@v1
              with:
                  toolchain: ${{ matrix.toolchain }}
                  override: true
                  components: rust-src

            - uses: Swatinem/rust-cache@v2

            - run: cargo build --verbose
