name: Build

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]

env:
    CARGO_TERM_COLOR: always

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - name: Install Rust
              run:
                  rustup toolchain install nightly --profile minimal
                  --no-self-update

            - name: Rust Cache
              uses: Swatinem/rust-cache@v2

            - run: rustc --version

            - name: Build
              run: cargo build --verbose
